[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_ldf_mode = deep+
lib_archive = no

lib_deps =
    robtillaart/AD9833
    U8g2
    