[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    robtillaart/AD9833@^0.4.1
    u8g2/U8g2@^2.35.19

[env:esp32-s2]
platform = espressif32
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    robtillaart/AD9833@^0.4.1
    u8g2/U8g2@^2.35.19
